services:

  nginx:
    image: containers.intersystems.com/intersystems/webgateway-nginx:latest-preview
    container_name: nginx-gateway
    depends_on:
      - iris
    ports:
      - ${NGINX_PORT_HTTP:-8080}:80
    volumes:
      - ./nginx/CSP.conf:/opt/nginx/conf/CSP.conf
      - ./nginx/CSP.ini:/opt/webgateway/bin/CSP.ini
    restart: unless-stopped

  iris:
    build:
      args:
        IMAGE: containers.intersystems.com/intersystems/irishealth:latest-em
      context: iris
    container_name: irishealth
    hostname: irishealth
    ports:
      - ${IRIS_PORT}:1972
    volumes:
      - iris-data:/iris-data
      - ./journal1:/journal1
      - ./journal2:/journal2
      - ./wij:/wij
      - ./iris/key/iris.key:/tmp/iris.key:ro
      - ./iris/python/iris_python_demo:/usr/irissys/mgr/python/iris_python_demo
      - ./merge.cpf:/merge.cpf
    command: --key /tmp/iris.key
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
      - ISC_DATA_DIRECTORY=/iris-data
      - ISC_CPF_MERGE_FILE=/merge.cpf

 
  webgateway:
    image: containers.intersystems.com/intersystems/webgateway:latest-em

    depends_on:
      - iris
    ports:
      - ${WEBGATEWAY_PORT_HTTP}:80
      - ${WEBGATEWAY_PORT_HTTPS}:443
    restart: unless-stopped
    environment:
    - ISC_CSP_CONF_FILE=/webgateway/CSP.conf
    - ISC_CSP_INI_FILE=/webgateway/CSP.ini
    volumes:
    - type: bind
      source: ./webgateway
      target: /webgateway
    networks:
      - default
 
volumes:
  iris-data:
  # journal1:
  # journal2:
  # wij: