{
 "title": "IRIS Overview",
 "tags": [
  "iris",
  "monitoring"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "20s",
 "panels": [
  {
   "title": "Gateway Scrape Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{job=~\"iris_metrics_.*\"})",
     "legendFormat": "scrape_up"
    }
   ]
  },
  {
   "title": "IRIS CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iris_cpu_usage", "legendFormat": "cpu_usage" }
   ]
  },
  {
   "title": "Gateway Connections to IRIS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "iris_csp_actual_connections", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Gateway Latency to IRIS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "iris_csp_gateway_latency", "legendFormat": "{{id}}" }
   ]
  }
 ]
}