# Included inside the default server block of /opt/nginx/conf/nginx.conf.

# Land on IRIS System Management Portal by default.
location = / {
    return 302 /csp/sys/UtilHome.csp;
}

# Route to IRIS through local CSPNSD (independent from apache webgateway).
location ^~ /csp/ {
    CSP On;
    CSPFileTypes csp cls zen cxw;
    CSPNSD_pass 127.0.0.1:7038;
    CSPNSD_response_headers_maxsize 8k;
    CSPNSD_connect_timeout 300s;
    CSPNSD_send_timeout 300s;
    CSPNSD_read_timeout 300s;
}

location ^~ /api/ {
    CSP On;
    CSPFileTypes *;
    CSPNSD_pass 127.0.0.1:7038;
    CSPNSD_response_headers_maxsize 8k;
    CSPNSD_connect_timeout 300s;
    CSPNSD_send_timeout 300s;
    CSPNSD_read_timeout 300s;
}

location = /api/monitor/metrics {
    CSP Off;
    default_type text/plain;
    add_header Cache-Control "no-cache";
    alias /metrics-cache/metrics.prom;
}

location ^~ /iris/ {
    CSP On;
    CSPFileTypes *;
    CSPNSD_pass 127.0.0.1:7038;
    CSPNSD_response_headers_maxsize 8k;
    CSPNSD_connect_timeout 300s;
    CSPNSD_send_timeout 300s;
    CSPNSD_read_timeout 300s;
}
